services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./custom:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    networks:
      - travel-network

  nginx:
    image: nginx:alpine
    container_name: travel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./custom:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - travel-network

  db:
    image: mysql:8.0
    container_name: travel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-travel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-travel_user}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - travel-network

  redis:
    image: redis:alpine
    container_name: travel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - travel-network

  adminer:
    image: adminer:latest
    container_name: travel-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - travel-network
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha-dark

networks:
  travel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
